import { type Locale } from "@/lib/i18n";

export const ROOT_AUTHOR_ID = "66687aadf862bd77";

const ADJECTIVES: Record<Locale, string[]> = {
  en: [
    "Adept",
    "Amber",
    "Arcane",
    "Breezy",
    "Calm",
    "Candid",
    "Careful",
    "Cobalt",
    "Curious",
    "Daring",
    "Deep",
    "Discrete",
    "Earnest",
    "Elder",
    "Exact",
    "Faint",
    "Feral",
    "Fluent",
    "Gentle",
    "Glassy",
    "Golden",
    "Grand",
    "Hardy",
    "Humble",
    "Icy",
    "Keen",
    "Kind",
    "Liminal",
    "Lucid",
    "Mild",
    "Mirthful",
    "Modern",
    "Narrow",
    "Nimble",
    "Noisy",
    "Oblique",
    "Patient",
    "Plain",
    "Proud",
    "Quiet",
    "Rare",
    "Rational",
    "Ready",
    "Sincere",
    "Slow",
    "Solid",
    "Sparse",
    "Steady",
    "Swift",
    "Tender",
    "Terse",
    "True",
    "Vast",
    "Vivid",
    "Warm",
    "Wary",
    "Witty",
    "Young",
    "Zesty",
  ],
  zh: [
    "沉静",
    "灵动",
    "好奇",
    "敏锐",
    "温和",
    "果敢",
    "清澈",
    "深邃",
    "明朗",
    "理性",
    "热忱",
    "谨慎",
    "幽默",
    "朴素",
    "坚定",
    "敏捷",
    "辽阔",
    "细腻",
    "清醒",
    "谦和",
    "耀眼",
    "柔软",
    "锋利",
    "轻盈",
    "古朴",
    "现代",
    "明快",
    "稀疏",
    "稳健",
    "迅捷",
    "真诚",
    "慷慨",
    "低调",
    "寡言",
    "温暖",
    "警觉",
    "年轻",
    "爽朗",
    "沉稳",
    "澄明",
    "敏思",
    "沉着",
    "明净",
    "笃定",
    "随和",
    "洒脱",
    "专注",
    "克制",
    "坦率",
    "锋芒",
    "从容",
    "微光",
    "澎湃",
    "轻巧",
    "厚重",
    "清雅",
    "炽热",
    "冷静",
    "鲜活",
    "平和",
    "坚定",
  ],
};

const NOUNS: Record<Locale, string[]> = {
  en: [
    "Anchor",
    "Apricot",
    "Atlas",
    "Beacon",
    "Birch",
    "Bridge",
    "Cipher",
    "Comet",
    "Cortex",
    "Crane",
    "Delta",
    "Dune",
    "Echo",
    "Ember",
    "Fable",
    "Fjord",
    "Flint",
    "Folio",
    "Grove",
    "Harbor",
    "Horizon",
    "Juniper",
    "Kernel",
    "Lattice",
    "Ledger",
    "Loom",
    "Maple",
    "Meadow",
    "Meridian",
    "Mirror",
    "Nexus",
    "Oak",
    "Opal",
    "Orbit",
    "Parcel",
    "Pillar",
    "Pine",
    "Prism",
    "Quarry",
    "Quill",
    "Reed",
    "Relay",
    "Ridge",
    "River",
    "Rune",
    "Saffron",
    "Sail",
    "Shell",
    "Signal",
    "Slate",
    "Spark",
    "Stone",
    "Thread",
    "Thistle",
    "Vessel",
    "Violet",
    "Wave",
    "Willow",
    "Wren",
  ],
  zh: [
    "锚",
    "杏",
    "星图",
    "灯塔",
    "白桦",
    "桥",
    "密语",
    "彗星",
    "皮层",
    "鹤",
    "三角洲",
    "沙丘",
    "回声",
    "余烬",
    "寓言",
    "峡湾",
    "燧石",
    "纸页",
    "林地",
    "港湾",
    "地平线",
    "杜松",
    "核心",
    "格栅",
    "账本",
    "织机",
    "枫",
    "草甸",
    "子午线",
    "镜",
    "枢纽",
    "橡",
    "欧泊",
    "轨道",
    "信封",
    "支柱",
    "松",
    "棱镜",
    "采石场",
    "羽笔",
    "芦苇",
    "中继",
    "山脊",
    "河",
    "符文",
    "藏红花",
    "帆",
    "贝壳",
    "信号",
    "板岩",
    "火花",
    "石",
    "线",
    "蓟",
    "器皿",
    "紫罗兰",
    "波",
    "柳",
    "鹪鹩",
  ],
};

function hexToBytes(hex: string): Uint8Array | null {
  if (typeof hex !== "string" || !/^[0-9a-f]+$/i.test(hex) || hex.length % 2 !== 0) return null;
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < bytes.length; i += 1) {
    bytes[i] = Number.parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  }
  return bytes;
}

export function pseudonymFromAuthorId(authorId: string, locale: Locale): string {
  if (authorId === ROOT_AUTHOR_ID) return locale === "zh" ? "议题" : "Topic";

  const bytes = hexToBytes(authorId);
  if (!bytes || bytes.length < 2) return locale === "zh" ? "匿名用户" : "Anonymous";

  const adjectiveList = ADJECTIVES[locale] ?? ADJECTIVES.en;
  const nounList = NOUNS[locale] ?? NOUNS.en;
  const adjective = adjectiveList[bytes[0] % adjectiveList.length];
  const noun = nounList[bytes[1] % nounList.length];

  if (!adjective || !noun) return locale === "zh" ? "匿名用户" : "Anonymous";
  return locale === "zh" ? `${adjective}${noun}` : `${adjective} ${noun}`;
}

